### ISSUE TITLE
Remove workaround to keep scone-cli up

### ISSUE THREAD

**Issue by Benardi** [ufcg-lsd/spire-scone-demo#1]
Right now a sleep command is being used to keep the scone-cli up:

```yaml
    spec:
      containers:
        - name: scone-cli
          image: registry.scontain.com:5050/sconecuratedimages/spire:network-shield-python-alpha3
          imagePullPolicy: IfNotPresent
          command: ["sleep"]
          args: ["1000000000"]
```

* If executed indefinitely the Deployment could at some point shut down. 

This could be replaced using Kubernetes features:

```yaml
    spec:
      containers:
        - name: scone-cli
          image: registry.scontain.com:5050/sconecuratedimages/spire:network-shield-python-alpha3
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          command: ["/bin/bash"]
```
